### ISSUE TITLE
Where's the timesheet data? 

### ISSUE THREAD

**Issue by fcouillard** [hubplanner/API#10]
Hi,
I can obtain most Project and Resource data from Hubplaner using PHP. I'm using stream_context_create and file_get_contents and it works well.

Now I need the timesheet data. So I call https://api.hubplanner.com/v1/timeentry with autorization and everything.

But it doesnt return anything. I get an empty json -> [].

In Hubplanner, my timesheet is full of fake data with submitted hours in the "General" category.

**Comment by thecodinglinguist** [comment]
Hi,

It is not possible to fetch all timeentries. That particular call should
return an "not implemented" message but I see now that it returns an empty
array. You have to use the search endpoint and you can pass in  resource id
and or project id, time range etc to narrow down your result.


Regards,
Jonas

On Wed, Sep 2, 2015 at 5:01 PM, fcouillard <notifications@github.com> wrote:

> Hi,
> I can obtain most Project and Resource data from Hubplaner using PHP. I'm
> using stream_context_create and file_get_contents and it works well.
>
> Now I need the timesheet data. So I call
> https://api.hubplanner.com/v1/timeentry with autorization and everything.
>
> But it doesnt return anything. I get an empty json -> [].
>
> In Hubplanner, my timesheet is full of fake data with submitted hours in
> the "General" category.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hubplanner/API/issues/10>.
>



-- 
Jonas Eliasson | + 46 733 20 41 11

**Comment by fcouillard** [comment]
It works nicely. Thanks a lot.

**Comment by fcouillard** [comment]
And how can I specify a time range?

**Comment by thecodinglinguist** [comment]
Hi,

There is date search example on the holiday section
https://github.com/hubplanner/API/blob/master/Sections/holidays.md


Best, Jonas

On Wed, Sep 2, 2015 at 9:55 PM, fcouillard <notifications@github.com> wrote:

> And how can I specify a time range?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hubplanner/API/issues/10#issuecomment-137226212>.
>



-- 
Jonas Eliasson | + 46 733 20 41 11

**Comment by fcouillard** [comment]
Works like a charm. Thank you.
