### ISSUE TITLE
500 internal server error when creating a project with useStatusColor

### ISSUE THREAD

**Issue by jakwo** [hubplanner/API#106]
Hi,

When creating a project and setting the field useStatusColor, the api returns an error. Posting without the field works:

![image](https://user-images.githubusercontent.com/11942234/215715774-5de37551-8baa-4bbf-8bf5-d2d5974bb4f6.png)

![image](https://user-images.githubusercontent.com/11942234/215715231-24539920-36a5-4278-91f4-efbb518aa04b.png)

This worked a few days ago.

**Comment by fikatown** [comment]
Hi @jakwo we don't this issue, would you be able to verify again and let us know if it still happens?

**Comment by jakwo** [comment]
@fikatown it seems to work again. Just checked.
