### ISSUE TITLE
Where are my Custom fields?

### ISSUE THREAD

**Issue by fcouillard** [hubplanner/API#11]
Hi,
is there a way to see the custom fields of my projects? I made a custom fields (Location) and assigned a value to each projects.

But it seems it doesn't show up when I get the data. 

Example:

            [_id] => 55dce4f3a11d4f62061f2df3
            [name] => Averna
            [links] => stdClass Object
                (
                    [link1] => 
                    [link2] => 
                    [link3] => 
                    [link4] => 
                    [link5] => 
                )

            [note] => Espace test pour le projet HubPlanner AVERNA
            [createdDate] => 2015-08-25T21:58:11.407Z
            [updatedDate] => 2015-09-02T13:51:59.632Z
            [workDays] => Array
                (
                    [0] => 
                    [1] => 1
                    [2] => 1
                    [3] => 1
                    [4] => 1
                    [5] => 1
                    [6] => 
                )

            [useProjectDays] => 1
            [budget] => stdClass Object
                (
                    [hasBudget] => 1
                    [projectHours] => stdClass Object
                        (
                            [active] => 
                            [hours] => 0
                        )

                    [cashAmount] => stdClass Object
                        (
                            [active] => 1
                            [amount] => 60000
                            [billingRate] => stdClass Object
                                (
                                    [useDefault] => 
                                    [rate] => 125
                                )
                        )
                )

            [useStatusColor] => 1
            [status] => STATUS_ACTIVE
            [useProjectDuration] => 1
            [start] => 2015-08-25
            [end] => 2015-10-15
            [resources] => Array
                (
                    [0] => 55dcdfa6134bef58069ecdb7
                    [1] => 55dce1d653ae7a5d06df83b9
                    [2] => 55dcdfa6134bef58069ecdbe
                    [3] => 55dcdfa6134bef58069ecdc0
                )

            [backgroundColor] => #81A489
            [projectCode] => 0071985
            [metadata] =>

**Comment by thecodinglinguist** [comment]
Hi,

Currently this is not possible. We have an upcoming API sprint where these
will be added. It has not been scheduled yet though so I can not give you a
specific date.


Best, Jonas

On Thu, Sep 3, 2015 at 7:22 PM, fcouillard <notifications@github.com> wrote:

> Hi,
> is there a way to see the custom fields of my projects? I made a custom
> fields (Location) and assigned a value to each projects.
>
> But it seems it doesn't show up when I get the data.
>
> Example:
>
>         [_id] => 55dce4f3a11d4f62061f2df3
>         [name] => Averna
>         [links] => stdClass Object
>             (
>                 [link1] =>
>                 [link2] =>
>                 [link3] =>
>                 [link4] =>
>                 [link5] =>
>             )
>
>         [note] => Espace test pour le projet HubPlanner AVERNA
>         [createdDate] => 2015-08-25T21:58:11.407Z
>         [updatedDate] => 2015-09-02T13:51:59.632Z
>         [workDays] => Array
>             (
>                 [0] =>
>                 [1] => 1
>                 [2] => 1
>                 [3] => 1
>                 [4] => 1
>                 [5] => 1
>                 [6] =>
>             )
>
>         [useProjectDays] => 1
>         [budget] => stdClass Object
>             (
>                 [hasBudget] => 1
>                 [projectHours] => stdClass Object
>                     (
>                         [active] =>
>                         [hours] => 0
>                     )
>
>                 [cashAmount] => stdClass Object
>                     (
>                         [active] => 1
>                         [amount] => 60000
>                         [billingRate] => stdClass Object
>                             (
>                                 [useDefault] =>
>                                 [rate] => 125
>                             )
>                     )
>             )
>
>         [useStatusColor] => 1
>         [status] => STATUS_ACTIVE
>         [useProjectDuration] => 1
>         [start] => 2015-08-25
>         [end] => 2015-10-15
>         [resources] => Array
>             (
>                 [0] => 55dcdfa6134bef58069ecdb7
>                 [1] => 55dce1d653ae7a5d06df83b9
>                 [2] => 55dcdfa6134bef58069ecdbe
>                 [3] => 55dcdfa6134bef58069ecdc0
>             )
>
>         [backgroundColor] => #81A489
>         [projectCode] => 0071985
>         [metadata] =>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hubplanner/API/issues/11>.
>



-- 
Jonas Eliasson | + 46 733 20 41 11

**Comment by fcouillard** [comment]
Thanks for the quick reply
