### ISSUE TITLE
OAuth 2.0 Sample

### ISSUE THREAD

**Issue by manuelvazquez** [hubplanner/API#14]
I am new to this, I would like to see a sample on how to authenticate.  I have the API key and I am using httpclient to interact with the hubplanner API.

Thanks,
Manuel

**Comment by thecodinglinguist** [comment]
Hi Manuel, 

I am not aware how to use that specific package. Here is a curl example that you can try from the console to get started. Should be very similar from any package/language. Set the required headers and use the appropriate request method. PUT/POST/GET 

curl -H "Content-Type: application/json" -H "Authorization: xxx" -X POST -d '{"status":"STATUS_ACTIVE"}' 
https://api.hubplanner.com/v1/resource/search

**Comment by manuelvazquez** [comment]
I am trying to use .Net to consume the api services.  Is there any .Net examples available? I think I am having trouble setting the default headers correctly.  I am getting a 400 error.  I am able to connect and get results using the Fiddler tool.

**Comment by thecodinglinguist** [comment]
Hi Manuel, 

Unfortunately we do not have any .NET examples! If you can print the request I might be able to see what is missing if that is of any help. 

Thanks,
Jonas

**Comment by manuelvazquez** [comment]
Imports System.Net.Http
Imports System.Net.Http.Headers
Imports System.Net.Http.Formatting
Imports Newtonsoft.Json.Formatting
Imports Newtonsoft.Json



Module Module1

    Sub Main()

        Dim t As Task = New Task(AddressOf DownloadPageAsync)
        t.Start()
        Console.WriteLine("Downloading Page ...")
        Console.ReadLine()

    End Sub

    Async Sub DownloadPageAsync()
        Dim page As String = "project"
        'Dim myUri As New Uri("https://api.hubplanner.com/v1/")
        Dim _ContentType As String = "application/json"

        Using client As HttpClient = New HttpClient()
            client.BaseAddress = New Uri("https://api.hubplanner.com/v1/")
            client.DefaultRequestHeaders.Add("Authorization", "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0NTk5ODQyMTEsInNjb3BlIjoiU0NPUEVfUkVBRCIsImlzcyI6IjU3MDU5NzQ4ZWZmYmQ4NTMwOGU0ZTgyMyIsInJlc291cmNlIjoiNTZiY2JjZmZiOTQxN2I4NTA2ZTVkMThlIn0.3ty0lOOtVTQF7RYrB7BghZTmBwo5il63dyN4sexlDzQ")
            client.DefaultRequestHeaders.Accept.Clear()
            client.DefaultRequestHeaders.Add("Accept", _ContentType)
            client.DefaultRequestHeaders.Add("User-Agent", "Hub Planner Sync App")

            'client.DefaultRequestHeaders.Authorization = New Headers.AuthenticationHeaderValue("Bearer", "eyJ0eXA ...........")

            Dim response As HttpResponseMessage = New HttpResponseMessage
            response.Headers.Clear()
            response.Content = New StringContent("")
            response.Content.Headers.ContentType = New MediaTypeHeaderValue("application/json")
            Await client.GetAsync(page)
            Dim content As HttpContent = response.Content
            Dim result As String = Await content.ReadAsStringAsync()
            If result IsNot Nothing Then
                Console.WriteLine(result + "...")
            End If
        End Using

    End Sub

End Module

**Comment by thecodinglinguist** [comment]
Hi Manuel,

I am not able to give you advice on this implementation as we are not working in .NET. For code specific help you have to seek advice from a .NET specific forum as I assume there is something missing in how you set the headers. 

Sorry I can not help you further. 

Jonas

**Comment by thecodinglinguist** [comment]
With printing the request I meant the actual request body and header to identify what is missing.

**Comment by manuelvazquez** [comment]
Thanks you Jonas.  I was able to figure out another way to access the api.  Once I get the solution to work, I will post the .net solution, maybe it will be helpful to other customers

Thanks,
Manuel

**Comment by thecodinglinguist** [comment]
That would be very appreciated!!

**Comment by mvahsen** [comment]
Hello manuelvazquez,
any updates on the .net solution?
 I'm currently getting the 500 error

**Comment by manuelvazquez** [comment]
Give me a couple of days and I will post the code I use to leverage the API.

Are you using the HTTP client or the Web Client?

**Comment by mvahsen** [comment]
Hi Manuel, was kind of tricky with HTTP client so I've managed finally with WebClient, I think the code is also shorter

 ```
private string Workin()
        {
            string myURI = "https://api.hubplanner.com/v1/project";
            using (System.Net.WebClient client = new System.Net.WebClient())
            {
                client.Headers.Add("user-agent", "My Hub Planner Import App (mvahsen@up-great.ch)");
                client.Headers.Add("Authorization", "eyJ0....");
                client.Headers.Add("Accept", "application/json");

                System.Collections.Specialized.NameValueCollection postData = new System.Collections.Specialized.NameValueCollection();
                postData.Add("name","Atlantis");
                postData.Add("projectCode", "123");
                
                string pagesource = Encoding.UTF8.GetString(client.UploadValues(myURI, postData));
                
            }
             return Context.Web.Url;
        }
```

**Comment by manuelvazquez** [comment]
Are you still getting the 500 error?  Your code is similar to mine

I use the client.downloadstring() and client.uploadstring() to post, get and put.  I can share samples if that would be helpful.

**Comment by thecodinglinguist** [comment]
Hi guys, 

Let me know if there is any remaining issues to connect and I will help to debug the requests you have tried. We will also make a better response to the 500 errors you have been getting. It will require a bit of refactor on our end. Thanks for the examples, I will add these to the documentation. 

Jonas
