### ISSUE TITLE
Groups are empty

### ISSUE THREAD

**Issue by manuelvazquez** [hubplanner/API#15]
I am getting empty json responses when i query either the project or resource group, although I have several groups defined and in use for both.

**Comment by thecodinglinguist** [comment]
Hi Manual, 

I have opened a ticket with our engineers. Looks like the "get all" requests have been disabled. 

Thanks! Jonas

**Comment by manuelvazquez** [comment]
any update?

**Comment by thecodinglinguist** [comment]
These are currently being refactored because of performance problems and we are very busy during the following weeks so I am not sure when these will be put back in place. Perhaps I can offer some kind of workaround. Can you let me know how you want to the group API calls?

**Comment by manuelvazquez** [comment]
We are planning to use the project groups to align active projects to a geography, we currently have three major geographies.  From a resource perspective we also would like to logically group resources to geography, regardless of the project geography.

Project alignment per geography is a higher priority.

**Comment by manuelvazquez** [comment]
ps.  we have a large volume of new projects (400+ per year), some lasting a short time, a few lasting over 6 months.  automating project creation is a priority to minimize logistical overhead.

**Comment by thecodinglinguist** [comment]
Hi Manuel, 
Just a quick note that I have been able to expedite this and we will include both project group and resource group GET calls, planned to be activated and live early this week. Search will not be implanted and is planned for our upcoming V2 of the API
