### ISSUE TITLE
Creating a new Project

### ISSUE THREAD

**Issue by manuelvazquez** [hubplanner/API#16]
1.-  Can you create more than 1 project at a time?

2.-  When you create a project, can you set any other properties other than Name:?

Thanks,
manuel

**Comment by thecodinglinguist** [comment]
Hi Manuel, 

You can pass in an array of projects instead of just one for the create call. You can see what properties you can pass in from the API docs. Let me know if you run into any issues.

**Comment by manuelvazquez** [comment]
Thanks, that helps.
