### ISSUE TITLE
Search Custom Fields

### ISSUE THREAD

**Issue by mvahsen** [hubplanner/API#17]
Hi there,

I need to create some sort of grouping for projects, so I thought I'll put some information in the customFields but can't search for it specifically.

thats the information I get with Postman and a Get / project

```
  `  "metadata": "",
    "customFields": [
      {
        "templateId": "57d94a5772ebc90508b29184",
        "_id": "57d9540372ebc90508b29ede",
        "templateType": "NUMBER",
        "templateLabel": "Gruppe",
        "value": "1"
      },`

```

If I do a POST with {"customFields" : "" }  then I get the response:

```
{
  "message": "This service has encountered an error. Please try again later.",
  "error": "should not contains property [\"customFields\"]",
  "code": "",
  "properties": "@",
  "version": 2
}
```

Is it possible to query in the customFields or to put some information and search for it in the metadata field instead of `customFields?

Best regards

Marco

**Comment by thecodinglinguist** [comment]
Hi Marco, 

Sorry for the late reply! We do not support search for Custom Fields unfortunately. We are working on API V2 which will have a lot of new features. I can check next week if we have something for the search queries to port over so you can use it here. 

Regards Jonas

**Comment by thomasmcgee** [comment]
Hi there,
I'm evaluating Hub Planner for my company. I'm very curious about this specific issue. Even though I see that custom fields are not searchable, are they returned via the api with the project and resource?
Thanks!

**Comment by thecodinglinguist** [comment]
Hi,

Thanks for your message. Yes the Custom Fields are returned for projects and resources through the API. Next version will also allow to search. 

Thanks, Jonas
