### ISSUE TITLE
How to query all TimeEntry for a date range

### ISSUE THREAD

**Issue by manuelvazquez** [hubplanner/API#18]
Is there a way to query at TimeEntry for a given date range?  In the documentation it seems to indicate there is a way to pull this, however there is no further documentation.

thanks
manuel

**Comment by thecodinglinguist** [comment]
Hi Manuel, 

Looks like that section is missing. It is absolutely possible to do. Here is an example. 
{"date":{"$gte": "2014-10-20", "$lte": "2014-10-27"}}

You can also add further filter for project / resource to make the search faster. 

/Jonas

**Comment by manuelvazquez** [comment]
Hi Jonas,

Is this a PUT for timeentry/search?

Regards,
manuel

**Comment by thecodinglinguist** [comment]
Hi,
The search calls are post requests. 
POST timeentry/search
Jonas

**Comment by manuelvazquez** [comment]
Thanks!
