### ISSUE TITLE
Missing example for getting time entries by daterane in timesheets.md

### ISSUE THREAD

**Issue by cpringles** [hubplanner/API#19]
In the [timesheets.md](https://github.com/hubplanner/API/blob/master/Sections/timesheets.md) there is no example below the following sentence:

> If you want to query all TimeEntry for a date range:

Are you able to provide an example that shows the syntax expected please?

Thanks in advance

**Comment by thecodinglinguist** [comment]
Hi, 

Thanks for letting me know, I will update this. 

Here is an example by resource and range. 
{resource:xx, date:{$gte: "2014-10-20", $lte: "2014-10-27"}}
