### ISSUE TITLE
No list of properties for TimeEntry object

### ISSUE THREAD

**Issue by cpringles** [hubplanner/API#20]
Would it be possible to include in [timesheets.md](https://github.com/hubplanner/API/blob/master/Sections/timesheets.md) a list of the properties, types and that are available in a TimeEntry?  A table similar to the one describing the values in the response when requesting a Booking in [Bookings.md](https://github.com/hubplanner/API/blob/master/Sections/bookings.md) would be ideal.

**Comment by thecodinglinguist** [comment]
Hi, 

Thanks for letting me know. I have updated the TS section.
