### ISSUE TITLE
Details of searchable properties for TimeEntries

### ISSUE THREAD

**Issue by cpringles** [hubplanner/API#21]
Could you add a table to [Timesheets.md](https://github.com/hubplanner/API/blob/master/Sections/timesheets.md#search-timeentry) showing which properties I can include in searches for TimeEntries?
A table similar to the one describing the searchable properties in [Bookings.md](https://github.com/hubplanner/API/blob/master/Sections/bookings.md) would be ideal.

**Comment by thecodinglinguist** [comment]
I have added this section now. You can use exactly the same query parameters.
