### ISSUE TITLE
project/search issues when filtering results

### ISSUE THREAD

**Issue by cpringles** [hubplanner/API#22]
I am having a strange issue when trying to search projects via the API.

If I try to search for all active projects with the following C# code:

```
            string url = baseURL + "/project/search";
            string json = "{\"status\": \"STATUS_ACTIVE\"}";
            HttpWebRequest webrequest = (HttpWebRequest)WebRequest.Create(url);
            webrequest.Method = "POST";
            webrequest.ContentType = "application/json";
            webrequest.Accept = "application/json";
            webrequest.UserAgent = "HubPlanner Time Entry Export (http://github.com/cpringles)";
            webrequest.Headers.Add("Authorization", RoApiKey);
            using (var streamWriter = new StreamWriter(webrequest.GetRequestStream()))
            {
                streamWriter.Write(json);
                streamWriter.Flush();
                streamWriter.Close();
            };
            Encoding enc = System.Text.Encoding.GetEncoding("utf-8");
            var webresponse = (HttpWebResponse)webrequest.GetResponse();
            StreamReader responseStream = new StreamReader(webresponse.GetResponseStream(), enc);
            string result = string.Empty;
            result = responseStream.ReadToEnd();
            webresponse.Close();

```

I get a HTTP OK response, but it only returns an empty array.
`[]`

If I change the json that I am sending to this:
`{\"status\": {\"$nin\" : \"STATUS_ARCHIVED\"}}`
The result is an HTTP 400 error - though as far as I can tell that should be a well formed request for all projects that are not archived.

If I GET all projects I can definitely see that there are many that have:
`status: "STATUS_ACTIVE"`

I have used effectively the same code to do a search of timeentries filtered to all entries post a specified date and that works as expected.

Any suggestions? 

Thanks

**Comment by cpringles** [comment]
Working with support overnight and they have identified the following:

1. There was a bug in the API that was preventing {"status": "STATUS_ACTIVE"} from working correctly.  This has been corrected and it now works.
2. There is an error in the documentation - when calling $in or $nin it is expecting an array.  So second example [here ](https://github.com/hubplanner/API/blob/master/Sections/project.md#search-projects)is incorrect and should include square brackets.

`{\"status\": {\"$nin\" :[\"STATUS_ACTIVE\"]}}`

However there is still an issue as the above line of code returns an array of all projects, including those with status: STATUS_ACTIVE.

**Comment by thecodinglinguist** [comment]
The remaining issues have been resolved and documentation updated.
