### ISSUE TITLE
How do you access custom rates set per project, per resource via the API

### ISSUE THREAD

**Issue by cpringles** [hubplanner/API#23]
We use custom rates for each resource on a project as typically different types of resource will have a different rate.

These are used correctly when we generate a report via the UI.  

However I can't see a way to access these custom rates via the API.  

I've seen the billingRate in the billing object returned but that only seems to include:
`billingRate: { useDefault: false, rate: 0 }`

Is there a way to access the custom rates configured?

Thanks.

**Comment by thecodinglinguist** [comment]
Hi Craig, 

We have enabled the resourceRates array for projects that contains the resources custom rates. This is read only and you have to use the UI to update these. For next version of the API we will also allow to set these properties. 

Jonas
