### ISSUE TITLE
Broken link and question

### ISSUE THREAD

**Issue by alnutile** [hubplanner/API#26]
Trying to figure out how to get a defaultRate.

```
        "billing": {
            "useDefault": true,
            "rate": 0
        },
```
I assume maybe https://github.com/hubplanner/API/blob/master/Sections/budgets.md it is here but here, as referenced from https://github.com/hubplanner/API/tree/master/Sections is broken.

Thanks
Al

**Comment by thecodinglinguist** [comment]
Hi, the useDefault indicates that the rate will be read from the project instead and if no rate is specified on the project the default company rate will be used. If you set a rate on the resource the bool will be false and the rate will be returned. All other instances the rate will be 0. 

Thanks for letting me know about the budget section missing. It is also scheduled for v2 of the API.
