### ISSUE TITLE
Billing Rate not seen in API?

### ISSUE THREAD

**Issue by alnutile** [hubplanner/API#27]
Maybe I am missing a setting.
If you look at this image, this person is set to $90 an hour.

<img width="688" alt="billing_screen" src="https://cloud.githubusercontent.com/assets/365385/22356851/531e68c0-e402-11e6-8d7b-5e036d24f23e.png">

But if you query that person in the API

```
{
  "_id": "56eb3dc1ed9236fa1735919f",
  "email": "foo@gmail.com",
  "metadata": "",
  "createdDate": "2016-03-17T23:29:05.180Z",
  "updatedDate": "2017-01-17T12:09:41.063Z",
  "note": "",
  "firstName": "Alfred",
  "lastName": "Nutile",
  "status": "STATUS_ACTIVE",
  "role": "ROLE_OWNER",
  "isProjectManager": true,
  ////////
  "billing": {
    "useDefault": true,
    "rate": 0
  },
  //////
  ],
  "useCustomAvailability": false
}
```

Any suggestions would be appreciated.

Thanks
Al

**Comment by thecodinglinguist** [comment]
Thanks for reporting. The API is currently going through a few changes as the underlying data structure has changed. I will make sure this will work in our next update (within the next hour)
