### ISSUE TITLE
Bookings and `workWeekDetails`

### ISSUE THREAD

**Issue by alnutile** [hubplanner/API#29]
Just wondering what `workWeekDetails` means. Did not see it in the docs.

For example

`STATE_DAY_MINUTE` is the state
so `stateValue` is `480` or 8 hours  

> the `stateValue` is the minutes per day for the booking [here](https://github.com/hubplanner/API/blob/master/Sections/bookings.md#get-all-project-bookings)

But then to look at `workWeekDetails` it would appear this resource is really only part time on this project, which makes sense since there are two overlapping results for this resource for this month.

still `6720` in the `bookedMinutes` comes back to 14 booked days * 8 hours a day * 60 minutes an hour leaving this resource seemingly full time booked.

```
{
        "_id": "foo",
        "title": "",
        "state": "STATE_DAY_MINUTE",
        "allDay": true,
        "scale": "SCALE_WEEK",
        "start": "2017-01-02T09:00",
        "end": "2017-01-20T18:00",
        "categoryTemplateId": "bar",
        "categoryName": "Planned work",
        "stateValue": 480,
        "resource": "foo",
        "project": "baz",
        "note": "",
        "details": {
            "offDaysCount": 0,
            "workDaysCount": 14,
            "holidayCount": 1,
            "workWeekDetails": [
                0,
                2,
                3,
                3,
                3,
                3,
                0
            ],
            "bookedMinutes": 6720,
            "budgetBookedAmount": 0
        },
        "createdDate": "2017-01-05T22:06:14.961Z",
        "updatedDate": "2017-01-10T16:59:50.998Z",
        "metadata": "",
        "backgroundColor": ""
    }
```

thanks

**Comment by thecodinglinguist** [comment]
Hi Alfred, 

The workWeekDetails is an array which represents the weeks 7 days and how many days of each weekday the booking is booked on. This is display logic for our Scheduler but it got exposed for another client and hence not documented.  

Ex. 
workWeekDetails[0] =  0 Sundays for this booking
workWeekDetails[1] = 2 Mondays for this booking (most likely there is a holiday on one Monday) 
workWeekDetails[2] = 3 Tuesdays for this booking.  
...

The resource is booked 8 hours each day according to this data and not part time. If you have another booking for the same range you would have to change both bookings to 4 hours each to make them part time.

Let me know if you have any more questions on that. 

Jonas

**Comment by alnutile** [comment]
@thecodinglinguist thanks!
