### ISSUE TITLE
Hitting the rate limits in the Harvest example

### ISSUE THREAD

**Issue by suzybates** [hubplanner/API#3]
I am trying to run the "harvest" example and I am receiving the 429 error.

added resource: forsander@fourkitchens.com
One job failed to process { [Error: cannot POST /v1/resource (429)]
  status: 429,
  text: undefined,
  method: 'POST',
  path: '/v1/resource' }

**Comment by thecodinglinguist** [comment]
Hi Suzy, 

You might hit the rate limit if you are running this on a large account Harvest account. The current example needs to be adjusted with a delay between each call. I will let you know once we have that updated.

**Comment by suzybates** [comment]
That doesn't really make sense.  You added a delay between each call in
December and things were working fine.  Now I am running it again and it
fails after one call.

**Comment by thecodinglinguist** [comment]
Alright correct. I will have to go through the source and check. Our tests are not failing. Have you also tried to post your own json body? or only used the example code? As I can see json failures that have not been caught by our validation checker which could give you the incorrect 429 response.

**Comment by suzybates** [comment]
I just downloaded your example code, added my credentials to the harvest.js file and ran it.

**Comment by thecodinglinguist** [comment]
We currently allow 2 requests / second. The timeout in the example was set to 1. And as the example is doing a search request and one update / create on each loop it went above the threshold. 

I have update the example to allow for this.
