### ISSUE TITLE
getting authorization error

### ISSUE THREAD

**Issue by marmikdesai** [hubplanner/API#32]
Hi,

I am trying to access data through API but getting authorization error on response. 

[test.txt](https://github.com/hubplanner/API/files/885249/test.txt)

here is response i am getting:- 
{
  "req": {
    "method": "GET",
    "url": "https://marmik.hubplanner.com/api/views/getHubControllerData"
  },
  "header": {
    "access-control-allow-origin": "https://hubplanner.com",
    "content-type": "text/html; charset=utf-8",
    "date": "Fri, 31 Mar 2017 10:06:45 GMT",
    "etag": "W/\"43-331Y7PkxDpQp0XTBTCJgKw\"",
    "server": "nginx",
    "set-cookie": [
      "connect.sid=s%3AwwXbApQP7QKw94SqIiopjQQtNmVqRoSo.iS8ABjMuxMnQ%2BxHx6lYQl6qS7HHo9pS1PuQ35nsMSmw; Domain=hubplanner.com; Path=/; HttpOnly"
    ],
    "vary": "Origin",
    "x-content-type-options": "nosniff",
    "x-dns-prefetch-control": "off",
    "x-download-options": "noopen",
    "x-frame-options": "SAMEORIGIN",
    "x-xss-protection": "1; mode=block",
    "content-length": "67",
    "connection": "Close"
  },
  "status": 401,
  "text": "you are not logged in or do not have authorization for this request"
}

can you please reply me asap? I am using node.js

**Comment by thecodinglinguist** [comment]
Please refer to the API documentation how to get started. This request is for the for the UI and can only be executed on our server.
