### ISSUE TITLE
unable to create resource with customFields

### ISSUE THREAD

**Issue by hturco** [hubplanner/API#33]
Hi @thecodinglinguist, @fikatown, @tomasz-sienn,

I'm evaluating Hub Planner for my company. This specific issue may be a blocker for me. I've created customFields in the console and assigned some to resources. I'm able to list all users and I see the customFields using **V1** of the API. I'm also able to create/update user through the API too.

**Issue:** I need to be able to import customFields through the API for resources. I tried doing it while creating a new resource, and also tried updating an existing resource by adding the customFields array. I couldn't get either way to work.

Thanks for your help

**Comment by thecodinglinguist** [comment]
Hi, 

Thanks for your message. Currently we do not have an API service to set Custom Fields. This is something we plan to develop but the development effort has yet not started. Potentially we can help you with a custom import meanwhile? Please contact hello@hubplanner.com if you have more questions around this.

Thanks, 
Jonas
