### ISSUE TITLE
Query Timesheets / Bookings that have recently been updated.

### ISSUE THREAD

**Issue by universlabs** [hubplanner/API#38]
Hi,

We maintain a tool that synchronises data from Hubplanner into our ERP system. Currently, it makes a lot of requests to Hubplanner to pull latest timesheets and bookings data because it needs to query *everything* in Hubplanner rather than just being able to query the latest changes.

Is there any way to query Timesheets and bookings based on their `updatedDate` property?

Thanks

**Comment by fikatown** [comment]
Hi,

Thanks for the feedback. This will be supported by COB today (CET). See updated docs here https://github.com/hubplanner/API/tree/master/Sections#sorting-results
