### ISSUE TITLE
Failed to create a time entry

### ISSUE THREAD

**Issue by Markovnin** [hubplanner/API#4]
I'm trying to create a timeentry via post request, but it returns 502 error all the time.

**Comment by thecodinglinguist** [comment]
Hi, It looks like our json validator are not doing its job and potentially passing through invalid requests. Could you post the request body so I can take a closer look. You can also email hello@hubplanner.com if you prefer depending on the content.

**Comment by Markovnin** [comment]
Emailed you more details
