### ISSUE TITLE
update via API issue

### ISSUE THREAD

**Issue by manuelvazquez** [hubplanner/API#42]
API interface has stoped working for all updates to the Project object

PUT https://api.hubplanner.com/v1/project/599848c42d7ac30c0623f9a7 HTTP/1.1
User-Agent: Fiddler
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOiIyMDE2LTA5LTI3VDE1OjA5OjI2LjIwNFoiLCJzY29wZSI6IlNDT1BFX1JFQURfV1JJVEUiLCJpc3MiOiI1NzA1OTc0OGVmZmJkODUzMDhlNGU4MjMiLCJyZXNvdXJjZSI6IjU2YmNiY2ZmYjk0MTdiODUwNmU1ZDE4ZSJ9.XTr_6E-jEJ2HW2qUUtAWExdmcvmBLQAx1bN48G0mPjE
Accept: application/json
Content-Type: application/json
Host: api.hubplanner.com
Content-Length: 1012

{"_id":"599848c42d7ac30c0623f9a7","name":"MJVTEST","links":{"link1":"","iconLink1":"","link2":"","iconLink2":"","link3":"","iconLink3":"","link4":"","iconLink4":"","link5":"","iconLink5":""},"note":"","createdDate":"2017-08-19T14:18:44.528Z","updatedDate":"2017-08-19T14:18:44.528Z","timeEntryEnabled":true,"timeEntryLocked":false,"timeEntryApproval":true,"projectCode":"123456789","timeEntryNoteRequired":false,"workDays":[false,true,true,true,true,true,false],"useProjectDays":false,"budget":{"hasBudget":false,"projectHours":{"active":false,"hours":0},"cashAmount":{"active":false,"amount":0,"currency":"USD","billingRate":{"useDefault":false,"rate":0,"id":null}}},"budgetHours":0,"budgetCashAmount":0,"budgetCurrency":"USD","companyBillingRateId":null,"useStatusColor":true,"status":"STATUS_ACTIVE","useProjectDuration":false,"start":null,"end":null,"resourceRates":[],"includeBookedTimeReports":true,"includeBookedTimeGrid":true,"projectManagers":[],"resources":[],"backgroundColor":"#4f81bd","metadata":""}

**creates the following output**

HTTP/1.1 400 Bad Request
Server: nginx
Date: Sat, 19 Aug 2017 14:21:10 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 221
Connection: keep-alive
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Access-Control-Allow-Origin: https://hubplanner.com
Vary: Origin
ETag: W/"dd-EB1Ir/cebYbcJHAEFxx3gA"
set-cookie: connect.sid=s%3AVwYMg2D3BGJwQyr1ixEgGCwnDCtDMpQb.90ArjB6IP0ACb18M2vghWqzSgcxqTrO0Xtb%2Flkz8%2BZ8; Domain=hubplanner.com; Path=/; HttpOnly

{"message":"The extension 'Resource Billing Rates' is required to perform this action. Please activate it and try again.","error":"EXTENSION_IS_NOT_ACTIVE","code":"A2424","properties":"Resource Billing Rates","version":2}

The only update in the JSON was the ProjectCode.  Other than that, it was a newly created project.

My app was updating the project code, project manager and resource.  It stopped working a few weeks back.  Right now I am unable to update the project via the API.  I am able to create a new project and delete an existing project.

**Comment by fikatown** [comment]
Hi,

Don't pass in the `resourceRates` parameter if you are not using that extension. Try that again and let us know.

**Comment by manuelvazquez** [comment]
I have been using this update statement for almost a year without issue.  Project code is a unique identifier that I have been updating with the statement I shared I the post.

**Comment by manuelvazquez** [comment]
Issue has not been resolved.  Still having the issue.

APi still does not work as it has been for the last several months.  Without a functioning api HubPlanner service is not longer viable as a service.
