### ISSUE TITLE
API being down too often

### ISSUE THREAD

**Issue by Markovnin** [hubplanner/API#5]
For the last couple of days I see about 4 out of 5 requests canceled. Is it possible to make API more stable?

**Comment by thecodinglinguist** [comment]
What kind of error are you seeing? If you are sending a lot of requests you will get a temporary block and a 429 response. While the API is in beta we have a pretty low threshold (2 r/s) this will be increased when more testing have been done. A delay in your client should take care of this. 

If you are getting other 50X server errors on what seems to be legit requests please forward them to hello@hubplanner.com so our engineers can take a look.

**Comment by Markovnin** [comment]
I'm building a timer app for our team. In order to allow it to group similar time entries (same resource, project, day and note), I need to first search for timeentries, and then either update existing one or create a new one.

Is it possible to increase the threshold to at least 4-5 r/s?

**Comment by thecodinglinguist** [comment]
We should be able to fit this into our next server maintenance release which is planned for this weekend. I will let you know when it is updated.

**Comment by Markovnin** [comment]
Thank you!

**Comment by thecodinglinguist** [comment]
We have upped the limit now to 4 r/s. We are working on a different rate limit solution which will allow better support for bursts of request. I hope this will be sufficient meanwhile.
