### ISSUE TITLE
Booking hour count by resource and project given a day

### ISSUE THREAD

**Issue by mergulhao** [hubplanner/API#51]
Hi Guys,

I want to get all bookings of a given day. Example:

Dec 5 - Resource 1 - Project X - 4h
Dec 5 - Resource 1 - Project Y - 4h
Dec 5 - Resource 2 - Project Y - 8h
Dec 5 - Resource 3 - Project Y - 8h

As I see, the only way to do it is to follow through all booking data and them transform your data. Am I correct? Is there an easier way?

Thanks.

**Comment by mergulhao** [comment]
Hey, can anyone help me? Thanks!

**Comment by fikatown** [comment]
Have you looked at the booking search? https://github.com/hubplanner/API/blob/master/Sections/bookings.md#search-bookings

**Comment by mergulhao** [comment]
@fikatown There is no answer to my question there. So I figure I'll have to convert your booking data.

**Comment by fikatown** [comment]
Yeah sorry you will need to manipulate the data returned how you need it.
