### ISSUE TITLE
Bug found when searching for a Booking scheduled on a holiday

### ISSUE THREAD

**Issue by mergulhao** [hubplanner/API#52]
Steps to reproduce the error:

1) Set a holiday;
2) Schedule a booking to that day (the resource worked in despite of the holiday);
3) Search for it on API using date range filter (POST booking/search with {"start": {"$lte": "2017-12-01"}, "end":{"$gte": "2017-12-01"} }).

The same behavior is seem in the web ui. The hours on the holiday's booking does not shows on reports and neither is deducted from budget amount.

Our domain is "impulso". You can check in the project "Hub Project Tester", booking on Dec 1. Can you check if I'm doing something wrong?

Thanks.

**Comment by fikatown** [comment]
Hi,

Scheduled time on holidays you set does not count. There is no scheduled time for those days and at the moment you cannot over ride it. Some customers use the "events" to set holidays instead of the global holiday setting.

**Comment by mergulhao** [comment]
@fikatown Ok. Anyway I think there is a problem related to date range filter. If I set a one day booking (example on Dec 1), there is no results if I search it with:

``POST booking/search with {"start": {"$gte": "2017-12-01"}, "end":{"$lte": "2017-12-01"} })``

That one day booking show in results if I add one day to the end entry, like this:

``POST booking/search with {"start": {"$gte": "2017-12-01"}, "end":{"$lte": "2017-12-02"} })``

Can you check it? Thanks.

**Comment by mergulhao** [comment]
@fikatown Can you check this? 👆
