### ISSUE TITLE
Getting client from project API

### ISSUE THREAD

**Issue by vgsantoniazzi** [hubplanner/API#53]
Hi!

I want get the client name from project through API. Seems the `project` API doesn't have client (or clients) listing and the `client` API doesn't have project (or projects) listing.

How can I do this?

**Comment by fikatown** [comment]
Hi,

Right now they are not connected on the API side like that. We will take a look.

**Comment by vgsantoniazzi** [comment]
@fikatown there's a plan to add it in the API ?

**Comment by jbayliss-opes** [comment]
this would be great to have, currently there seems to be no way of linking a project to a client or visa-versa when using the API.

**Comment by jbayliss-opes** [comment]
Never mind, its not documented, but its possible to get the clients attached to a project by sending a GET request to /project/project_id/client
