### ISSUE TITLE
Search TimeEntry - Status not searchable

### ISSUE THREAD

**Issue by W1R3D-Code** [hubplanner/API#54]
Docs say status should be searchable but I just get an error;

POST timeentry/search

`{"status":{"$in":"UNSUBMITTED"}}`

results in:

```
{
    "message": "This service has encountered an error. Please try again later.",
    "error": "should not contains property [\"status\"]",
    "code": "",
    "properties": "@",
    "version": 2
}
```

**Comment by WojtekBator** [comment]
it's now fixed, go and check. If You specify "$in" operator, make sure the value is an array, not just a string (in Your case ["UNSUBMITTED"] would be ok)
