### ISSUE TITLE
Cannot set `useProjectDuration`

### ISSUE THREAD

**Issue by mohamdaoui** [hubplanner/API#65]
Hi, I am trying to set the `useProjectDuration` to `true` in the `POST /project` endpoint, and I keep getting this:
```
{
    "message": "This service has encountered an error. Please try again later.",
    "error": "PROPERTY_ASSERTION_ERROR",
    "code": "A02",
    "properties": {
        "additionalInformation": {
            "message": "useProjectDuration needs to be a boolean",
            "requestData": {
                "name": "test",
                "start": "2014-09-04T13:52:17.740Z",
                "end": "2014-09-06T13:52:17.740Z",
                "useProjectDuration": "true"
            }
        }
    },
    "version": 2
}
```
I am passing a boolean and it seems it is received as a String!
I should note that I am using the exact same format to pass booleans in other calls and they are working, like the `POST /resource` and passing `isProjectManager` as true.

Is there something special with this property?

**Comment by mohamdaoui** [comment]
I solved this by passing a raw body instead of a form!

**Comment by WojtekBator** [comment]
you should now be fine also when sending a form.
