### ISSUE TITLE
Need commas in your Holiday Response structure

### ISSUE THREAD

**Issue by suzybates** [hubplanner/API#7]
[{ _id: '54785431e91e5ead13e8d841',
  name: 'Christmas',
  date: '2014-12-25',
  metadata: '' 
}]

**Comment by suzybates** [comment]
And it's missing some fields and isn't sending the ID

[{"name":"Thanksgiving","date":"2014-11-27","metadata":"","createdDate":"2015-02-13T17:14:32.234Z","updatedDate":"2015-03-24T20:10:22.584Z"}]

**Comment by thecodinglinguist** [comment]
Thanks for reporting, this is now resolved
