### ISSUE TITLE
Webhooks: Get Person Updating or Deleting a Booking like bookingCreatorName

### ISSUE THREAD

**Issue by cysk** [hubplanner/API#75]
Currently the Webhook only provides the bookingCreatorName (e.g. "John Doe") but not the Person deleting or updating a record.

As we know from the web app interface, this information is available already.

This Issue requests adding fields naming the updating as well as the deleting user for a booking record.

**Comment by nmhub** [comment]
In addition to the webhook, it would be useful to get the resource id of the persons that created and last updated a booking via /resource/

**Comment by WojtekBator** [comment]
done

**Comment by nmhub** [comment]
If I do GET /booking, I see the same as documented here: https://github.com/hubplanner/API/blob/master/Sections/bookings.md

There is a bookingCreatorId field, but nothing to indicate who updated/edited the booking. I tested with a different user to edit the booking than created the booking too.

**Comment by WojtekBator** [comment]
I've done it for webhooks as the issue specifies. It's also possible to add to bookings API. Please, open issue for the API part

**Comment by cysk** [comment]
@WojtekBator can you please update the corresponding documentation at: https://github.com/hubplanner/API/blob/master/Sections/webhooks.md

**Comment by cysk** [comment]
Referencing the given topic of this issue, the name of the user updating or deleting an issue is what has been requested.
Additional Info: If the webhook is not pushing Usernames to the webhook endpoint, the endpoint needs to do an additional api call to get the name of the User who created/updated/deleted a ressource booking.
To provide a clean webhook approach, either...
- only push user id's of users creating/updating/deleting a booking or 
- just push usernames of users creating/updating/deleting a booking to the webhook endpoint.

_To be compatible with current integrations, please add user-Ids for "createdBy" and "deletedBy" in case of create or delete operations and keep the field bookingCreatorName for create operations._

**Comment by cysk** [comment]
Webhooks currently do not provide the desired information right now.

**Currenty Status:**

**booking.create**
_lastUpdatedById_: Currently undefined
_lastUpdatedByName_: Currently undefined

**booking.update**
_lastUpdatedById_: provides User-ID as expected
_lastUpdatedByName_: provides Users Full Name as expected

**booking.delete**
_lastUpdatedById_: Currently undefined
_lastUpdatedByName_: Currently undefined

_I_f _lastUpdatedById_ and _lastUpdatedByName_ should be available in all three cases to reduce and unify code on webhook target system.

Any way, currently we are not able to get the Name or ID of a User deleting a booking via Webhook push.

**Comment by fikatown** [comment]
Thanks guys, we are taking a look.
