### ISSUE TITLE
Get for all Bookings and Post for filtered bookings are not returning the same results

### ISSUE THREAD

**Issue by suzybates** [hubplanner/API#8]
The first row is the (first) result for the GET of all bookings.
The second row is the (first) result for the POST of the Project's bookings

[{"_id":"549454bbf71d9fc906115394","title":"","state":"STATE_DAY_MINUTE","allDay":true,"scale":"SCALE_DAY","start":"2015-01-15 10:00","end":"2015-01-16 17:00","stateValue":60,"resource":"54369ccfb96408730ce84657","project":"5436ac27b96408730ce8eac3","note":"","details":{"workDaysCount":2,"offDaysCount":0,"workWeekDetails":[0,0,0,0,1,1,0],"bookedMinutes":120,"budgetBookedAmount":0},"createdDate":"2014-12-19T16:39:23.501Z","updatedDate":"2014-12-19T16:40:04.063Z","metadata":""},
[{"_id":"549454bbf71d9fc906115394","title":"","state":"STATE_DAY_MINUTE","allDay":true,"scale":"SCALE_DAY","start":"2015-01-15 10:00","end":"2015-01-16 17:00","stateValue":60,"resource":"54369ccfb96408730ce84657","project":"5436ac27b96408730ce8eac3","note":"","createdDate":"2014-12-19T16:39:23.501Z","updatedDate":"2014-12-19T16:40:04.063Z","metadata":""},

The details are missing from the second result.

Please fix asap!!!!

**Comment by thecodinglinguist** [comment]
Hi Suzy, 

Thanks for reporting, we have added the details properties to the search endpoint. Please let us know if any issues. 

/Jonas

**Comment by suzybates** [comment]
thanks, that fixed it!
