### ISSUE TITLE
EXCEPTION: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by fcouillard** [hubplanner/API#9]
Hi,
I'm trying to do a simple get action. I'm starting from the harvest example.

As I can't use the async module for some reason, I'm trying to update restClient.js to https module instead.

So 

        request
            .get(hubPlannerConfig.domain + apiPath + entityPath)
            .set({'content-type': hubPlannerConfig.contentType})
            .set({'authorization': hubPlannerConfig.authorization})
            .end(function (error, data) {
                if (error || data.statusCode !== 200) {
                    callback(error || data.error, null);
                } else {
                    callback(null, data.body);
                }
            });

become

		var options = {
			hostname : hubPlannerConfig.domain + apiPath + entityPath,
			headers: { 
				"Content-Type" : hubPlannerConfig.contentType,
				"Accept" : hubPlannerConfig.contentType,
				"Authorization" : hubPlannerConfig.authorization,
				"User-Agent" : "My request (***@***.com)"
			}
		};
		
		function reply (response) {
			response.setEncoding('utf8');
			
			response.on("data", callback(null, data.body));
			response.on("error", callback(error || data.error, null));
		}
		
		https.get(options, reply);

And it just keep saying 

EXCEPTION: getaddrinfo ENOTFOUND https://api.hubplanner.com/v1/resource/

What am I doing wrong?

I'm quite a Node.js noob.

Thanks

**Comment by thecodinglinguist** [comment]
Hi!

I am not that knowledgable with the https module so difficult to know what
you are doing wrong. The error itself seems to point to that your call is
not finding the server so make sure that the address is correct.

I would have to recreate the test to be able to help you and we are
currently in the middle of a big release. Let me know how you get along and
perhaps I can take a look next week for you.


Regards, Jonas

On Tue, Sep 1, 2015 at 10:05 PM, fcouillard <notifications@github.com>
wrote:

> Hi,
> I'm trying to do a simple get action. I'm starting from the harvest
> example.
>
> As I can't use the async module for some reason, I'm trying to update
> restClient.js to https module instead.
>
> So
>
>     request
>         .get(hubPlannerConfig.domain + apiPath + entityPath)
>         .set({'content-type': hubPlannerConfig.contentType})
>         .set({'authorization': hubPlannerConfig.authorization})
>         .end(function (error, data) {
>             if (error || data.statusCode !== 200) {
>                 callback(error || data.error, null);
>             } else {
>                 callback(null, data.body);
>             }
>         });
>
> become
>
>     var options = {
>         hostname : hubPlannerConfig.domain + apiPath + entityPath,
>         headers: {
>             "Content-Type" : hubPlannerConfig.contentType,
>             "Accept" : hubPlannerConfig.contentType,
>             "Authorization" : hubPlannerConfig.authorization,
>             "User-Agent" : "My request (***@***.com)"
>         }
>     };
>
>     function reply (response) {
>         response.setEncoding('utf8');
>
>         response.on("data", callback(null, data.body));
>         response.on("error", callback(error || data.error, null));
>     }
>
>     https.get(options, reply);
>
> And it just keep saying
>
> EXCEPTION: getaddrinfo ENOTFOUND https://api.hubplanner.com/v1/resource/
>
> What am I doing wrong?
>
> I'm quite a Node.js noob.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hubplanner/API/issues/9>.
>



-- 
Jonas Eliasson | + 46 733 20 41 11

**Comment by fcouillard** [comment]
Hi, thanks for the reply.

I just dropped Node.js and tried with PHP and it mostly work. But I have another problem so I'll open another issue.
