### ISSUE TITLE
Notes not being passed to timesheets from bookings

### ISSUE THREAD

**Issue by GISShawn** [hubplanner/API#91]
I'm writing a script that queries the HubPlanner API for timesheet information, formats it and prepares it for upload to our timekeeping system.  Some of our booking entries contain notes, which are not required for every booking, yet are not passed to the corresponding timesheet entry.  Would it be possible to get any booking notes passed to the timesheet without having them being required.  Thank you in advance!!

**Comment by fikatown** [comment]
Hi, this is more a feature question than an API so I am passing to our team to take a further look. thanks for the suggestion.
