### ISSUE TITLE
webhook.md: Clarify lastUpdatedById & lastUpdatedByName meaning in booking.update

### ISSUE THREAD

**Issue by cysk** [hubplanner/API#93]
Hi,

the _booking.update_ event data-fields _lastUpdatedById_ and _lastUpdatedByName_ in webhook-payload are not clearly defined. 

Please optimize (clarify) the documentation, because when a booking is updated it is not clear whether the data-fields _lastUpdatedById_ and _lastUpdatedByName_ contain the updating user id and name of the _current_ update action or the data of the _last_ update action that has happened before. 

After testing it seems that it contains the current updating user.

Thanks

**Comment by cysk** [comment]
Any update regarding this issue?

**Comment by fikatown** [comment]
it is the user which last updated the booking.
