### ISSUE TITLE
Webhook: Provide deletedById and deletedByName in booking.delete event

### ISSUE THREAD

**Issue by cysk** [hubplanner/API#94]
Hi,

currently we do not receive data about the user who deleted a booking when the event _booking.delete_ or event _booking.delete.multiple_ is triggered.

Can you please add _deletedById_ and _deletedByName_ for events _booking.delete_ and _booking.delete.multiple_.

Thanks

**Comment by cysk** [comment]
Any update on this issue?

**Comment by nmhub** [comment]
I hear it's in the pipeline and might be delivered withing a couple of weeks

**Comment by fikatown** [comment]
Apologies gents this took so long. Now supported

`deletedById` and `deletedByResourceName`
