### ISSUE TITLE
Creation of HubPlanner Project -- Adding it to group

### ISSUE THREAD

**Issue by alepetrangelo** [hubplanner/API#96]
Im trying to create a new project in HubPlanner and associate it to our specific group we have for our comapany. 

Upon attemping to create a Hubplanner project we response from the API saying:
`{"message":"Provided property is incorrect - name.","error":"PROPERTY_ASSERTION_5RROR","code":"A02","properties":{"additionalInformation":{"message":"name","projectId":null}},"version":2}`

Thus then when we try to associate this project to our group we get another error comaplaining about not have the necessary _ID which to my knowledge is generated by the server:

`{"message":"Provided id is incorrect. Please review your request. project-managers","error":"OBJECTID_INCORRECTLY_FORMATTED","code":"A04","properties"version":2}
`
 This project was started over two years ago so im wondering if you guys had any idea what is causing this response from the API.

**Comment by fikatown** [comment]
Hi,

To add a project to a group, just follow this https://github.com/hubplanner/API/blob/master/Sections/groups.md#add-a-project-to-a-projectgroup
