### ISSUE TITLE
Webhook listing

### ISSUE THREAD

**Issue by andrecavallari** [hubplanner/API#97]
Please, provide a webhook list, then we can list the id's and we can update or delete old webhooks! 

Thanks!

**Comment by fikatown** [comment]
Hi,

You will find that list here https://github.com/hubplanner/API/blob/master/Sections/webhooks.md

**Comment by andrecavallari** [comment]
@fikatown, there is not a `list` of webhooks created with each `id` in this link unfortunately, if I create one and dont store it's id anywhere i can never remove that webhook... Also I've noticed that the custom fields wont come with webhooks payloads, is there a way to have it?
