### ISSUE TITLE
Getting 400 Bad Request when trying to create even the simplest resource via API

### ISSUE THREAD

**Issue by davesag** [hubplanner/API#98]
I am writing code to extract data from our current system and import it into Hub Planner.

Most things work now but I am having trouble posting a `resource`

```json
{
  "firstName": "Testy",
  "lastName": "McTestface",
  "email": "testy.mctestface@test.tes"
}
```

This is giving me a `400 Bad Request` error.

### Notes

- I've set the headers etc correctly
- other posts work just fine (including bulk uploading of projects with properly mapped `customFields` etc)
- I've also looked at issue #92  but my issue does not appear to be rate-limiting as other posts / deletions / etc all work fine.

What am I doing wrong?

Cheers Dave

**Comment by nmhub** [comment]
Try with the object inside an array:
```
[{
    "firstName": "Testy",
    "lastName": "McTestface",
    "email": "testy.mctestface@test.tes"
}]
```

**Comment by davesag** [comment]
It turns out my issue was bad data having been uploaded in a previous run that was causing the API server to choke.  I manually deleted that buggered resource using the Hub Planner web UI and then resources would happily upload.
