### ISSUE TITLE
Rate limits are inconsistently documented and are set way too low

### ISSUE THREAD

**Issue by davesag** [hubplanner/API#99]
The rate limits are  inconsistently documented and set way too low.

1. 50 per 5 seconds - what even is this?  Why not just say 10 per second?
2. 6000 per day - maybe fine for a small user but when writing a bulk uploader and debugging it this limit gets reached very quickly.
3. [2 requests per second per account](https://github.com/hubplanner/API#error-codes--responses) - seriously? That's ridiculous and contradicts `1` above.

Maybe if the API itself was more consistent (ie why does bulk uploading projects return `_id` fields but bulk uploading resources does not, and why can only resources and projects be bulk uploaded?  I have several hundreds of resources and projects to upload and it takes forever (at 2 requests per second I make several cups of tea per run) and I hit the daily rate limit after a few hours of testing (because I also have to delete things one by one).

APIs I am used to dealing with offer rate limits around 1000 requests per second for high volume APIs and even lower volume APIs still usually run 100s of requests per second and many also do not throttle reads, only writes.

A daily limit of maybe 100,000 would seem a lot more reasonable to me.

Also it would be really helpful to know when the rate limit is going to reset?  Is it midnight? GMT? UTC? my local time? some other timezone?

**Comment by fikatown** [comment]
Hi @davesag thanks for your feedback. We will look into the limits to make sure they are more consistent maybe the docs are a little behind and we are moving them to a new system.

Can I ask about your bulk upload or update. Can you not just do 1 call and pass them in an array? using PATCH if you just updating something

e.g. 

`[
    {
        "_id": "5f69edb573582132e894dcb8",
        "firstName": "New Name 1"
    },
   {
        "_id": "5f69edb573582162e894dcb9",
        "firstName": "New Name 2"
    }
]` 

similar with projects you can use PATCH to bulk update instead of looping API Calls?

Our server time uses UTC and you can always contact our support if you need more limits increases for some job you are doing and we will be happy to help.

**Comment by davesag** [comment]
> Can I ask about your bulk upload or update. Can you not just do 1 call and pass them in an array? using PATCH if you just updating something

I was following the documentation and under some time pressure to get stuff working so didn't really have the time to poke around in the dark trying undocumented features.

The project is done now and all our data was eventually imported to HubPlanner.  I have no idea if we decided to proceed with actually using it however as I've since moved onto a different project.

**Comment by fikatown** [comment]
hi, ah ok cool no worries. Sorry we have been slow to reply here. The issue tracking on Git is something we are trying to manage better now, we were thrown a bit off course this year with COVID issues, but putting a new focus on the API and docs and as above moving to a more streamlined approach with Postman for the docs. Thanks for your understanding and quick reply @davesag

**Comment by davesag** [comment]
@fikatown no worries.  It's been quite the year eh.

I recommend using a tool like OpenAPI (Aka Swagger) to formalise and specify your API.
